
binds:
- port: 10000
  listeners:
  - routes:
    - backends:
      - mcp:
          name: default
          targets:
          - name: sequentialthinking
            stdio:
              cmd: docker
              args:
              - run
              - --rm
              - -i
              - ghcr.io/dimetron/mcp-servers/sequentialthinking:local
              env: {}
          - name: memory
            stdio:
              cmd: docker
              args:
              - run
              - --rm
              - -i
              - ghcr.io/dimetron/mcp-servers/memory:local
              env: {}
          - name: time
            stdio:
              cmd: docker
              args:
                - run
                - --rm
                - -i
                - ghcr.io/dimetron/mcp-servers/time:local
              env: { }
      policies:
        cors:
          allowOrigins:
          - '*'
          allowHeaders:
          - mcp-protocol-version
          - content-type
          - cache-control
