global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'litellm'
    static_configs:
      - targets: ['litellm:4000']  # Assuming Litellm exposes metrics at port 4000
  - job_name: 'agentgateway'
    static_configs:
      - targets: ['agentgateway:15020']  # Assuming Litellm exposes metrics at port 15020